import type { Metadata } from "next";
import { Epilogue } from "next/font/google";
import "./globals.css";

import { Providers } from "./providers";
import { useTheme } from "next-themes";

const epilogue = Epilogue({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      // data-dark-mode={theme === "dark" ? "true" : "false"}
    >
      <body
        className={` relative h-screen overflow-hidden bg-light text-dark dark:bg-dark-2 dark:text-light ${
          process.env.NODE_ENV == "development" ? "debug-screens" : ""
        }`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
