import { FiHome, FiTool, FiInfo, FiPhone } from "react-icons/fi";
import { FaTools } from "react-icons/fa";
import { AiOutlineProject } from "react-icons/ai";
import { MdInfo } from "react-icons/md";

export const skillNames: string[] = [
  "nodejs",
  "typescript",
  "nextjs",
  "reactjs",
  "mongodb",
  "tailwindcss",
  "css",
  "redux",
  "figma",
  "python",
  "sql",
  "machine_learning",
  "django",
  "java",
  "cpp",
  "kafka",
  "golang",
  "html",
  "redis",
  "docker",
  "cassandra",
  "react_native",
  "angular",
  "vuejs",
  "flutter",
  "swift",
  "kotlin",
  "php",
  "ruby",
  "perl",
  "csharp",
  "visual_studio",
  "intellij_idea",
  "vs_code",
  "sublime_text",
  "atom",
  "android_studio",
  "xcode",
  "netbeans",
  "eclipse",
  "mysql",
  "postgresql",
  "sqlite",
  "oracle",
  "firebase",
  "heroku",
  "git",
  "github",
  "bitbucket",
  "dockerhub",
  "kubernetes",
  "aws",
  "google_cloud",
  "linux",
];
export const themes: string[] = [
  "purple",
  "amber",
  "lime",
  "indigo",
  "pink",
  "cyan",
];
