import { FiHome, FiTool, FiInfo, FiPhone } from "react-icons/fi";
import { FaTools } from "react-icons/fa";
import { AiOutlineProject } from "react-icons/ai";
import { MdInfo } from "react-icons/md";

export const skillNames: string[] = [
  "nodejs",
  "typescript",
  "nextjs",
  "reactjs",
  "mongodb",
  "tailwindcss",
  "css",
  "redux",
  "figma",
  "python",
  "sql",
  "machine_learning",
  "django",
  "java",
  "cpp",
  "kafka",
  "golang",
  "html",
  "redis",
  "docker",
  "cassandra",
  "react_native",
  "angular",
  "vuejs",
  "flutter",
  "swift",
  "kotlin",
  "php",
  "ruby",
  "perl",
  "csharp",
  "visual_studio",
  "intellij_idea",
  "vs_code",
  "sublime_text",
  "atom",
  "android_studio",
  "xcode",
  "netbeans",
  "eclipse",
  "mysql",
  "postgresql",
  "sqlite",
  "oracle",
  "firebase",
  "heroku",
  "git",
  "github",
  "bitbucket",
  "dockerhub",
  "kubernetes",
  "aws",
  "google_cloud",
  "linux",
];
export const themes: string[] = [
  "amber",
  "emerald",
  "red",
  "purple",
  "lime",
  "indigo",
  "pink",
  "cyan",
  "blue",
  "violet",
];

export const gradientColorMap: { [key: string]: string } = {
  amber: " from-amber-600 to-pink-500",
  emerald: " from-emerald-600 to-lime-500",
  red: " from-red-600 to-amber-500",
  purple: " from-purple-600 to-indigo-500",
  lime: " from-lime-600 to-cyan-500",
  indigo: " from-indigo-600 to-cyan-500",
  pink: " from-pink-600 to-purple-500",
  cyan: " from-cyan-600 to-emerald-500",
  blue: " from-blue-600 to-cyan-500",
  violet: " from-violet-600 to-pink-500",
};
